name: Report generation

on:
  push:
    branches:
      - main

jobs:
  make_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Generate overview
        run: |
          ./plots metrics.csv --outdir report --gh-token ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: report # The folder the action should deploy.

